"""create_code_relations_table

Revision ID: 9a9aab037662
Revises: a502db0b6d3c
Create Date: 2026-07-10 15:59:14.642023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9aab037662'
down_revision: Union[str, Sequence[str], None] = 'a502db0b6d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=1000), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_name', sa.String(length=1000), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_info', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_relations_id'), 'code_relations', ['id'], unique=False)
    op.create_index(op.f('ix_code_relations_relation_type'), 'code_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_code_relations_repository_id'), 'code_relations', ['repository_id'], unique=False)
    op.create_index(op.f('ix_code_relations_session_id'), 'code_relations', ['session_id'], unique=False)
    op.create_index(op.f('ix_code_relations_source_name'), 'code_relations', ['source_name'], unique=False)
    op.create_index(op.f('ix_code_relations_target_name'), 'code_relations', ['target_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_relations_target_name'), table_name='code_relations')
    op.drop_index(op.f('ix_code_relations_source_name'), table_name='code_relations')
    op.drop_index(op.f('ix_code_relations_session_id'), table_name='code_relations')
    op.drop_index(op.f('ix_code_relations_repository_id'), table_name='code_relations')
    op.drop_index(op.f('ix_code_relations_relation_type'), table_name='code_relations')
    op.drop_index(op.f('ix_code_relations_id'), table_name='code_relations')
    op.drop_table('code_relations')
    # ### end Alembic commands ###
