"""Add User Auth and Multi-Tenancy

Revision ID: d3f058035a58
Revises: 9a9aab037662
Create Date: 2026-07-22 17:10:22.011352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f058035a58'
down_revision: Union[str, Sequence[str], None] = '9a9aab037662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # Handle existing data by making it nullable first
    op.add_column('repositories', sa.Column('user_id', sa.UUID(), nullable=True))
    
    # Delete any existing data that doesn't have a user, as it's invalid in the new schema
    # (Must delete relations and chunks first to avoid FK errors)
    op.execute("DELETE FROM code_relations")
    op.execute("DELETE FROM document_chunks")
    op.execute("DELETE FROM repositories")

    # Now make it non-nullable
    op.alter_column('repositories', 'user_id', nullable=False)
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_foreign_key(None, 'repositories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_column('repositories', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
